# Generated by Django 3.1.2 on 2021-03-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsubstitute',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodsubstitute',
            name='nutriscore',
            field=models.CharField(max_length=200),
        ),
    ]
