# Generated by Django 3.1.2 on 2021-04-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210404_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='nutriscore',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
